apiVersion: apps/v1
kind: Deployment
metadata:
  name: calci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calci
  template:
    metadata:
      labels:
        app: calci
    spec:
      containers:
      - name: calci
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080